title: Bugo Site
baseURL: "/"
languageCode: en
summaryLength: 25
googleAnalytics: ''
paginate: 10
sectionPagesMenu: footer
enableEmoji: true
outputs:
  home:
    - html
    - rss
    - json
  taxonomy:
    - html
    - rss
    - json